fix(breaking): ACNA-1682 - HTTP/HTTPS proxy agent logic
adobe/aio-lib-core-networking pull request #18
Opened 2022-06-08 08:20 UTC by amulyakashyap09

# [ACNA-1682](https://jira.corp.adobe.com/browse/ACNA-1682) | HTTP/HTTPS Proxy Agent Logic

## Description

https://github.com/adobe/aio-lib-core-networking/blob/b8dca7b8c0ab6c91b5fad0343a84635f1690ecb0/src/ProxyFetch.js#L79-L83

This bases whether to use HTTP/HTTPS proxy based on what the proxy protocol is, however this logic is wrong, it should be based on what the end point protocol is:

| Type            | Proxy | Server |
|-----------------|-------|--------|
| HttpProxyAgent  | HTTP  | HTTP   |
| HttpProxyAgent  | HTTPS | HTTP   |
| HttpsProxyAgent | HTTP  | HTTPS  |
| HttpsProxyAgent | HTTPS | HTTPS  |

As a result, using an http proxy and connecting to an https endpoint causes the logic to pick HttpProxyAgent which then returns an error from the server as we are trying to connect to it via non HTTPS methods

Fixes #16

## Related Issue

https://jira.corp.adobe.com/browse/ACNA-1682

## Motivation and Context

## How Has This Been Tested?

- Code has been test on local machine
- Unit tests are passing

## Screenshots (if appropriate):
<img width="1036" alt="Screenshot 2022-06-08 at 1 46 47 PM" src="https://user-images.githubusercontent.com/19944275/172567515-aa245f2e-2759-42d0-b2c8-ce02c64788ad.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-06-08 11:41 UTC, shazron approved these changes

2022-06-08 11:48 UTC, moritzraho approved these changes

2022-06-08 12:23 UTC, moritzraho requested changes
After discussing with @amulyakashyap09 moving this from approved to request changes, needs unit tests to capture the new behavior and avoid future bugs (http vs https resource url).

also I tend to think that we should remove proxyAgent from the exposed the API, otherwise changes like this one are considered breaking changes. cc @shazron for additional feedback

2022-06-09 02:49 UTC, shazron commented
@moritzraho I flagged this as breaking in the title and description. Can we move forward on  merging this fix?

2022-06-09 09:48 UTC, moritzraho commented
Sure make sense, thanks for the comments

2022-06-09 09:48 UTC, moritzraho commented
still waiting on some tests to approve tho

2022-06-09 14:48 UTC, shazron commented
@amulyakashyap09 can you add explicit tests that tests the situations you described in the table?

2022-06-15 11:10 UTC, moritzraho approved these changes
lgtm thanks for going through the changes !

2022-06-15 11:17 UTC, merged